Document: chert
Title: Debian chert Manual
Author: <insert document author here>
Abstract: This manual describes what chert is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/chert/chert.sgml.gz

Format: postscript
Files: /usr/share/doc/chert/chert.ps.gz

Format: text
Files: /usr/share/doc/chert/chert.text.gz

Format: HTML
Index: /usr/share/doc/chert/html/index.html
Files: /usr/share/doc/chert/html/*.html
