Document: hornstone
Title: Debian hornstone Manual
Author: <insert document author here>
Abstract: This manual describes what hornstone is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hornstone/hornstone.sgml.gz

Format: postscript
Files: /usr/share/doc/hornstone/hornstone.ps.gz

Format: text
Files: /usr/share/doc/hornstone/hornstone.text.gz

Format: HTML
Index: /usr/share/doc/hornstone/html/index.html
Files: /usr/share/doc/hornstone/html/*.html
